- hosts: master:slave
  user: vagrant
  tasks:
  - name: Install MariaDB repository
    yum_repository: name=MariaDb description=repository baseurl='http://yum.mariadb.org/10.3.24/centos7-amd64' gpgcheck=no enabled=yes
  - name: Install MariaDB Server
    yum: name=mariadb-server state=latest
  - name: Install python module
    yum: name=MySQL-python state=latest
  - name: Start mariadb service
    service: name=mariadb state=started 
  - name: Create replication account
    mysql_user: name=repl host="%" password=s3cr3tPaSSwordR priv="*.*:REPLICATION SLAVE" state=present
  - name: Create readwrite user
    mysql_user: name=rwuser host="%" password=s3cr3tPaSSwordR priv=*.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP state=present
  - name: Modify configuration file to listen on all interfaces
    lineinfile: dest=/etc/my.cnf.d/server.cnf regexp="^bind-address" line="bind-address=0.0.0.0"
- hosts: master
  user: vagrant
  tasks:
  - name: Modify configuration file to setup server ID
    lineinfile: dest=/etc/my.cnf.d/server.cnf regexp="^#server-id" line="server-id=1"
  - name: Activate master binlog
    lineinfile: dest=/etc/my.cnf.d/server.cnf regexp="^#log-bin" line="log-bin"
  - name: Restart mysql service
    service: name=mariadb state=restarted
  - name: Reset master binlog
    command: /usr/bin/mysql -u root -e "RESET MASTER"
- hosts: slave
  user: vagrant
  tasks:
  - name: Modify configuration file to setup server ID
    lineinfile: dest=/etc/my.cnf.d/server.cnf regexp="^#server-id" line="server-id=2"
  - name: Setup replication
    command: /usr/bin/mysql -uroot -e "CHANGE MASTER TO master_host='192.168.10.2', master_user='repl', master_password='s3cr3tPaSSwordR', master_use_gtid=current_pos"
  - name: Restart mysql service
    service: name=mariadb state=restarted
